version: '3.7'

services:
  app:
    image: joshrpowell/rails_app:v1
    build:
      context: .
    command: ["rails", "server"]
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - RAILS_ENV
    ports:
      - 3000:3000

  pg:
    image: postgres:10.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

volumes:
  pg-data:
